# Generated by Django 4.2.4 on 2023-09-01 17:44

from django.db import migrations, models
import django.db.models.deletion
import store.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='color cost per m2')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='cost per m3')),
                ('destiny', models.PositiveIntegerField(default=0, verbose_name='destiny in kg/m3 units')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(choices=[(1, 'S'), (5, 'M'), (10, 'L'), (15, 'Xl'), (20, 'Xxl'), (25, 'Xxxl')], default=5, verbose_name='purchase size with volume in m3')),
                ('code', models.CharField(default=store.utils.hex_code, max_length=32, unique=True, verbose_name='unique code')),
                ('state', models.PositiveSmallIntegerField(choices=[(-1, 'rejected'), (0, 'waited'), (1, 'accepted'), (2, 'sent')], default=0, verbose_name='state')),
                ('address', models.CharField(max_length=512, verbose_name='address inside Westland')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.color', verbose_name='color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.material', verbose_name='material')),
            ],
            options={
                'ordering': ['-date_created', 'date_updated'],
            },
        ),
        migrations.CreateModel(
            name='PreparedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(choices=[(1, 'S'), (5, 'M'), (10, 'L'), (15, 'Xl'), (20, 'Xxl'), (25, 'Xxxl')], default=5, verbose_name='purchase size with volume in m3')),
                ('description', models.TextField(max_length=512, verbose_name='description')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.color', verbose_name='color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.material', verbose_name='material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=512, verbose_name='consultant comment')),
                ('is_allowed', models.BooleanField(default=None, null=True, verbose_name='consulted and allowed')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.purchase', verbose_name='purchase')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
