# Generated by Django 4.2.4 on 2023-09-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedpurchase',
            name='title',
            field=models.CharField(default='Prepared purchase', max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.purchase', verbose_name='purchase'),
        ),
    ]
